# Generated by Django 3.1.2 on 2020-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
    ]
