# Generated by Django 3.1.2 on 2020-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
