# Generated by Django 3.1.2 on 2020-12-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlatform', '0002_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
