# Generated by Django 3.1.2 on 2020-12-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlatform', '0003_auto_20201226_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.FileField(blank=True, default=True, upload_to='images'),
            preserve_default=False,
        ),
    ]
