# Generated by Django 3.1.2 on 2020-12-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlatform', '0005_auto_20201226_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, upload_to='https://event-p.herokuapp.com/media/images'),
        ),
    ]
