# Generated by Django 3.1.2 on 2020-12-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlatform', '0008_auto_20201227_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
